services:
  borisfx-rlm:
    image: borisfx-rlm
    platform: linux/amd64
    build:
      tags:
        - borisfx-rlm
      x-bake:
        platforms:
          - linux/amd64
    volumes:
      - ./licenses:/licenses
      - ./logs:/logs
      - ./certs:/certs
    hostname: ${HOSTNAME}
    mac_address: ${HOSTID}
    ports:
      - 5053:5053
      - 5054:5054
      - 5153:5153
